### ISSUE TITLE
SyncNodes - failing to save remote node update

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/dpn-sync#47]
```
E, [2016-11-03T10:30:58.780765 #30701] ERROR -- : #<RuntimeError: Failed to update aptrust node:
{:status=>"500", :error=>"Internal Server Error"}>
```

Backtrace details:
```
/opt/app/dpn/dpn-sync/releases/20161102230620/lib/dpn/workers/sync_nodes.rb:21:in `save_remote_node'
/opt/app/dpn/dpn-sync/releases/20161102230620/lib/dpn/workers/sync_nodes.rb:12:in `sync'
/opt/app/dpn/dpn-sync/releases/20161102230620/lib/dpn/workers/nodes.rb:74:in `block in sync_data'
/opt/app/dpn/dpn-sync/releases/20161102230620/lib/dpn/workers/nodes.rb:74:in `map'
/opt/app/dpn/dpn-sync/releases/20161102230620/lib/dpn/workers/nodes.rb:74:in `sync_data'
/opt/app/dpn/dpn-sync/releases/20161102230620/lib/dpn/workers/nodes.rb:57:in `sync'
/opt/app/dpn/dpn-sync/releases/20161102230620/lib/dpn/workers/sync_worker.rb:18:in `perform'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:155:in `execute_job'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:136:in `block (3 levels) in process'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/logging.rb:32:in `with_context'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:131:in `block (2 levels) in process'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:171:in `stats'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:130:in `block in process'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:122:in `process'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:81:in `process_one'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/processor.rb:69:in `run'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:17:in `watchdog'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/sidekiq-4.2.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

Need to debug the code in lib/dpn/workers/sync_nodes.rb

**Comment by dazza-codes** [comment]
A quick debug console session on SDR dpn-dev:

``` ruby
> sdr = DPN::Workers.nodes.local_node
> aptrust = DPN::Workers.nodes.remote_node('aptrust')
> response = aptrust.client.node('aptrust')
=> #<DPN::Client::Response:0x00000004c72000
 @body=
  {:name=>"APTrust",
   :namespace=>"aptrust",
   :api_root=>"https://dpn-demo.aptrust.org",
   :ssh_pubkey=>"",
   :created_at=>"2015-12-16T15:57:46Z",
   :updated_at=>"2016-10-20T21:28:27Z",
   :replicate_from=>["tdr", "hathi", "chron"],
   :replicate_to=>["tdr", "hathi", "chron"],
   :restore_from=>["tdr", "hathi", "chron"],
   :restore_to=>["tdr", "hathi", "chron"],
   :protocols=>["rsync"],
   :fixity_algorithms=>["sha256"],
   :storage=>{:region=>"va", :type=>"glacier"}},
 @cached_json=
  "{\"name\":\"APTrust\",\"namespace\":\"aptrust\",\"api_root\":\"https://dpn-demo.aptrust.org\",\"ssh_pubkey\":\"\",\"created_at\":\"2015-12-16T15:57:46Z\",\"updated_at\":\"2016-10-20T21:28:27Z\",\"replicate_from\":[\"tdr\",\"hathi\",\"chron\"],\"replicate_to\":[\"tdr\",\"hathi\",\"chron\"],\"restore_from\":[\"tdr\",\"hathi\",\"chron\"],\"restore_to\":[\"tdr\",\"hathi\",\"chron\"],\"protocols\":[\"rsync\"],\"fixity_algorithms\":[\"sha256\"],\"storage\":{\"region\":\"va\",\"type\":\"glacier\"}}",
 @status=200>
> aptrust.update  # essentially gets the data as above
=> true
> aptrust.to_hash  # should match the data as above (except for authorization stuff)
=> {:namespace=>"aptrust",
 :api_root=>"https://dpn-demo.aptrust.org/",
 :auth_credential=>"snipped from this github issue",
 :name=>"APTrust",
 :ssh_pubkey=>"",
 :created_at=>"2015-12-16T15:57:46Z",
 :updated_at=>"2016-10-20T21:28:27Z",
 :replicate_from=>["tdr", "hathi", "chron"],
 :replicate_to=>["tdr", "hathi", "chron"],
 :restore_from=>["tdr", "hathi", "chron"],
 :restore_to=>["tdr", "hathi", "chron"],
 :protocols=>["rsync"],
 :fixity_algorithms=>["sha256"],
 :storage=>{:region=>"va", :type=>"glacier"}}

> # OK so far, but now it will fail to PUT this data to the local node
> response = sdr.client.update_node(aptrust.to_hash)
=> #<DPN::Client::Response:0x00000005483898 @body={:status=>"500", :error=>"Internal Server Error"}, @cached_json="{\"status\":\"500\",\"error\":\"Internal Server Error\"}", @status=500>
```

OK, so now looking at the SDR-dev dpn-server log, it shows more details about this error:

```
I, [2016-11-03T15:40:03.148344 #10420]  INFO -- : {"method":"PUT","path":"/api-v2/node/aptrust","format":"*/*","controller":"NodesController","action":"update","status":500,"error":"ActiveRecord::StatementInvalid: Mysql2::Error: Column 'storage_region_id' cannot be null: UPDATE `nodes` SET `ssh_pubkey` = '', `storage_region_id` = NULL, `storage_type_id` = NULL, `api_root` = 'https://dpn-demo.aptrust.org/', `updated_at` = '2016-11-03 22:40:03' WHERE `nodes`.`id` = 7","duration":53.4,"view":0.0,"db":14.97,"params":{"namespace":"aptrust","api_root":"https://dpn-demo.aptrust.org/","auth_credential":"b9e60308c5ad425da1ee25f00b524773cb589a0547e4","name":"APTrust","ssh_pubkey":"","created_at":"2015-12-16T15:57:46Z","updated_at":"2016-10-20T21:28:27Z","replicate_from":["tdr","hathi","chron"],"replicate_to":["tdr","hathi","chron"],"restore_from":["tdr","hathi","chron"],"restore_to":["tdr","hathi","chron"],"protocols":["rsync"],"fixity_algorithms":["sha256"],"node":{"namespace":"aptrust","name":"APTrust","ssh_pubkey":"","created_at":"2015-12-16T15:57:46Z","updated_at":"2016-10-20T21:28:27Z","api_root":"https://dpn-demo.aptrust.org/","auth_credential":"b9e60308c5ad425da1ee25f00b524773cb589a0547e4"}},"@timestamp":"2016-11-03T22:40:03.146Z","@version":"1","message":"[500] PUT /api-v2/node/aptrust (NodesController#update)"}
F, [2016-11-03T15:40:03.151347 #10420] FATAL -- : 
ActiveRecord::StatementInvalid (Mysql2::Error: Column 'storage_region_id' cannot be null: UPDATE `nodes` SET `ssh_pubkey` = '', `storage_region_id` = NULL, `storage_type_id` = NULL, `api_root` = 'https://dpn-demo.aptrust.org/', `updated_at` = '2016-11-03 22:40:03' WHERE `nodes`.`id` = 7):
  app/models/node.rb:58:in `block in update_with_associations'
  app/models/node.rb:167:in `set_attributes_with_associations'
  app/models/node.rb:57:in `update_with_associations'
  app/controllers/nodes_controller.rb:43:in `update'
```

**Comment by dazza-codes** [comment]
So, the problem here is that the local node cannot interpret the storage region|type data from the remote node.  In this case, the failure to update the node data is the expected behavior, so it's not strictly a bug.  However, for the existing dpn-sync code, this failure to update one of the nodes interferes with updating any of the other nodes; in this regard, it's a bug in dpn-sync.
