### ISSUE TITLE
Error in bag rsync operation

### ISSUE THREAD

**Issue by dazza-codes** [sul-dlss/dpn-sync#48]
```
2016-11-04T17:14:02.259Z 12121 TID-ouymwfj8g WARN: RuntimeError: Failed retrieve rsync: Error in rsync protocol data stream
2016-11-04T17:14:02.259Z 12121 TID-ouymwfj8g WARN: /opt/app/dpn/dpn-sync/releases/20161103203612/lib/dpn/workers/bag_rsync.rb:24:in `block in rsync'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/rsync-1.0.9/lib/rsync.rb:18:in `run'
/opt/app/dpn/dpn-sync/releases/20161103203612/lib/dpn/workers/bag_rsync.rb:23:in `rsync'
/opt/app/dpn/dpn-sync/releases/20161103203612/lib/dpn/workers/bag_replication.rb:153:in `retrieve_rsync'
/opt/app/dpn/dpn-sync/releases/20161103203612/lib/dpn/workers/bag_replication.rb:122:in `retrieve'
/opt/app/dpn/dpn-sync/releases/20161103203612/lib/dpn/workers/bag_replication.rb:49:in `replicate'
/opt/app/dpn/dpn-sync/releases/20161103203612/lib/dpn/workers/bag_worker.rb:15:in `perform'
```

**Comment by dazza-codes** [comment]
Debug process on SDR dpn-dev:

``` sh
[dpn@dpn-dev ~]$ cd dpn-sync/current/
[dpn@dpn-dev current]$ RACK_ENV=production bundle exec rackup -d
```

``` ruby
sdr = DPN::Workers.nodes.local_node
chron = DPN::Workers.nodes.remote_node('chron')
chron_bags = []
sdr.client.bags({ admin_node: chron.namespace }) {|resp| chron_bags << resp.body }
chron_bag_uuid = chron_bags.sample(1).first[:uuid]
query = { bag: chron_bag_uuid, from_node: chron.namespace, to_node: sdr.namespace }
replications = []
chron.client.replications(query) {|resp| replications << resp.body }

repl = replications.sample(1).first
replication = DPN::Workers::BagReplication.new(repl)
replication.id
#=> "c26d55c7-4679-495d-9b72-78fd2b72535b"
replication.bag_id
#=> "1f806acb-52be-40d8-a9f9-2b6891cc62cf"
replication.link
#=> "sdr@dpn-registry-dev.ucsd.edu:/export/outgoing/bags/test/1f806acb-52be-40d8-a9f9-2b6891cc62cf.tar"
staging_path = replication.send(:staging_path)
#=> "/dpn_data/staging/c26d55c7-4679-495d-9b72-78fd2b72535b"

syncer = DPN::Workers::BagRsync.new(replication.link, staging_path, 'retrieve')
syncer.send(:options)
#=> "--copy-dirlinks --copy-unsafe-links --partial --quiet --recursive --archive"

# The syncer is not composing an rsync command with the correct ssh options, because
# the ruby process is not able to confirm that the ssh identity file exists, eg
File.exist? "/home/dpn_user/.ssh/id_rsa"
#=> false

# Because of that, the ssh retrieve command is empty, eg
ssh = DPN::Workers::BagSSH.new
ssh.retrieve_command
# => ""
```

**Comment by dazza-codes** [comment]
This is not yet fixed, the latest exception detail is:

```
2016-11-12T00:55:32.646Z 15490 TID-kbjhs WARN: RuntimeError: Failed retrieve rsync: Unknown Error, options: --copy-dirlinks --copy-unsafe-links --partial --quiet --recursive --arc
hive -e 'ssh -o PasswordAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -l sdr -i /dpn_data/sdr/.ssh/id_rsa'
2016-11-12T00:55:32.646Z 15490 TID-kbjhs WARN: /opt/app/dpn/dpn-sync/releases/20161110232404/lib/dpn/workers/bag_rsync.rb:26:in `block in rsync'
/opt/app/dpn/dpn-sync/shared/bundle/ruby/2.3.0/gems/rsync-1.0.9/lib/rsync.rb:18:in `run'
/opt/app/dpn/dpn-sync/releases/20161110232404/lib/dpn/workers/bag_rsync.rb:23:in `rsync'
/opt/app/dpn/dpn-sync/releases/20161110232404/lib/dpn/workers/bag_replication.rb:153:in `retrieve_rsync'
/opt/app/dpn/dpn-sync/releases/20161110232404/lib/dpn/workers/bag_replication.rb:120:in `retrieve'
/opt/app/dpn/dpn-sync/releases/20161110232404/lib/dpn/workers/bag_replication.rb:49:in `replicate'
/opt/app/dpn/dpn-sync/releases/20161110232404/lib/dpn/workers/bag_worker.rb:15:in `perform'
```

**Comment by dazza-codes** [comment]
This has been fixed by replacing the `rsync` gem with system commands instead.  That gem is not as well developed as initially thought, it does not support all rsync operations from remote hosts.
